version: "3.8"
services:
  elasticsearch:
    image: elasticsearch:7.12.0
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./database:/usr/share/elasticsearch/data
  application:
    image: idt-app
    depends_on:
      - elasticsearch
    ports:
      - 80:80
