version: '3'

services:
  elasticsearch:
    image: elasticsearch:7.12.0
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./database:/usr/share/elasticsearch/data

  preprocessing:
    image: idt-preprocessing
    container_name: preprocessing
    depends_on:
      - elasticsearch
    command: bash -c "
        python3 idt-preprocessing.py -w 20220301.simple -n 1000 -k 10 -t 45 --min 1 --max 2 &&
        python3 create_database.py
      "
    volumes:
      - ./import:/data/import
      - ./export:/data/export
    working_dir: /data
    stdin_open: true
    tty: true
